version: 0.2


env:
  variables:
    POSTGRES_DB: "root"
    POSTGRES_USER: "root"
    POSTGRES_PASSWORD: "root"
    DJANGO_SUPERUSER_USERNAME: "admin"
    DJANGO_SUPERUSER_PASSWORD: "admin"
    DJANGO_SUPERUSER_EMAIL: "admin@admin.com"

phases:
  install:
    commands:
      - echo "Installing Docker..."
      - apt-get update && apt-get install -y docker.io
      - echo "Installing Docker Compose..."
      - curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
      - chmod +x /usr/local/bin/docker-compose

  pre_build:
    commands:
      - echo "Logging into Amazon ECR..."
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 390402549525.dkr.ecr.ap-south-1.amazonaws.com
      - echo "Setting up environment variables..."
      - echo "POSTGRES_DB=mydatabase" > .env
      - echo "POSTGRES_USER=myuser" >> .env
      - echo "POSTGRES_PASSWORD=mypassword" >> .env
      - echo "DJANGO_SECRET_KEY=2e125c+cv*+4u+lyc(its004u440rtp3a)w_=7luyy0+z#3%ub" >> .env
      - echo "DJANGO_DEBUG=True" >> .env
      - echo "Building Docker images..."
      - docker-compose -f docker-compose.yml build

  build:
    commands:
      - echo "Tagging Docker images..."
      - docker tag django-react-postgres_backend:latest 390402549525.dkr.ecr.ap-south-1.amazonaws.com/my-app-repo:backend-latest
      - docker tag django-react-postgres_frontend:latest 390402549525.dkr.ecr.ap-south-1.amazonaws.com/my-app-repo:frontend-latest
      - docker tag django-react-postgres_nginx:latest 390402549525.dkr.ecr.ap-south-1.amazonaws.com/my-app-repo:nginx-latest
      - echo "Pushing Docker images to ECR..."
      - docker push 390402549525.dkr.ecr.ap-south-1.amazonaws.com/my-app-repo:backend-latest
      - docker push 390402549525.dkr.ecr.ap-south-1.amazonaws.com/my-app-repo:frontend-latest
      - docker push 390402549525.dkr.ecr.ap-south-1.amazonaws.com/my-app-repo:nginx-latest

  post_build:
    commands:
      - echo "Build and push completed successfully."

artifacts:
  files:
    - '**/*'
